Feature/observable key groups collection tests
Softeq/XToolkit.WhiteLabel pull request #328
Opened 2020-08-18 10:25 UTC by nkrisko

### Description

Unit Tests for ObservableKeyGroupsCollection

### API Changes

 None

### Platforms Affected

- Core (all platforms)

### Behavioral/Visual Changes

None

### Before/After Screenshots

Not applicable

### PR Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/Softeq/XToolkit.WhiteLabel/blob/master/.github/CONTRIBUTING.md) document
- [ ] My code follows the [code styles](https://github.com/Softeq/dotnet-guidelines)
- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-10-26 15:09 UTC, wcoder requested changes
Looks good, but doesn't work with Android/iOS Playground samples (grouped list/collection).

Also, I put some comments.

2020-10-26 15:09 UTC, wcoder commented on Softeq.XToolkit.Common/Collections/ObservableKeyGroupsCollection.cs
> +            public Group(KeyValuePair<TKey, IList<TValue>> keyValuePair)
Stiles: properties under the ctor

2020-10-26 18:03 UTC, nkrisko commented on Softeq.XToolkit.Common/Collections/ObservableKeyGroupsCollection.cs
> +                clearGroupEvent); // check, how check key ?
yep

2020-10-28 07:28 UTC, nkrisko commented on Softeq.XToolkit.Common/Collections/ObservableKeyGroupsCollection.cs
> +            var newItems = new Collection<(int, IReadOnlyList<TKey>)>
It was before me

2020-10-30 15:02 UTC, wcoder approved these changes

2020-10-30 15:02 UTC, merged