Add tests for Timer and TimerFactory
Softeq/XToolkit.WhiteLabel pull request #338
Opened 2020-08-25 15:32 UTC by AlexandraMash

### Description

Added tests for Timer and TimerFactory

### API Changes
 
 None

### Platforms Affected

- Core (all platforms)

### Behavioral/Visual Changes

None

### Before/After Screenshots

Not applicable

### PR Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/Softeq/XToolkit.WhiteLabel/blob/master/.github/CONTRIBUTING.md) document
- [x] My code follows the [code styles](https://github.com/Softeq/dotnet-guidelines)
- [x] Targets the correct branch
- [x] Tests are passing (or failures are unrelated)

2020-08-25 16:29 UTC, SavikPavel approved these changes

2020-08-25 18:38 UTC, wcoder requested changes

2020-08-25 18:38 UTC, wcoder commented on Softeq.XToolkit.Common.Tests/Timers/TimerTests/TimerTests.cs
> +
need case: double call `Start()`

2020-08-25 18:38 UTC, wcoder commented on Softeq.XToolkit.Common.Tests/Timers/TestFunctionClass.cs
> +        public Task Function()
seems like this class can be replaced via mock object

2020-08-25 18:38 UTC, wcoder commented on Softeq.XToolkit.Common/Timers/Timer.cs
> +        public int Interval { get; }
I think no need to expose these properties, it's out of the scope of current class

2020-08-25 18:38 UTC, wcoder commented on Softeq.XToolkit.Common/Timers/Timer.cs
>          {
can be added optional `ILogger` property to use in `FireAndForget`

2020-08-25 18:38 UTC, wcoder commented on Softeq.XToolkit.Common.Tests/Timers/TimerTests/TimerTests.cs
> +
need case: Start_After_Dispose

2020-08-25 18:38 UTC, wcoder commented on Softeq.XToolkit.Common.Tests/Timers/TimerTests/TimerTests.cs
> +            var taskRef = new TaskReference(functionClass.Function);
`taskRef` can be shared

2020-08-26 15:04 UTC, wcoder approved these changes

2020-08-27 13:11 UTC, SavikPavel approved these changes

2020-08-27 13:14 UTC, merged