Add ObservableObject tests
Softeq/XToolkit.WhiteLabel pull request #339
Opened 2020-08-25 21:43 UTC by wcoder

### Description

Add tests:
- ObservableObject
- GenericEventArgsTests

### PR Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/Softeq/XToolkit.WhiteLabel/blob/master/.github/CONTRIBUTING.md) document
- [x] My code follows the [code styles](https://github.com/Softeq/dotnet-guidelines)
- [x] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-08-26 11:24 UTC, AlexandraMash requested changes

2020-08-26 11:24 UTC, AlexandraMash commented on Softeq.XToolkit.Common.Tests/ObservableObjectTests/ObservableObjectTests.cs
> +                Assert_PropertyChanged(obj, string.Empty, () =>
Is it ok to have an assert inside an assert?

2020-08-26 11:24 UTC, AlexandraMash commented on Softeq.XToolkit.Common.Tests/ObservableObjectTests/ObservableObjectTests.cs
> +        }
Wouldn't it be useful to test VerifyPropertyName separately?

2020-08-26 15:03 UTC, AlexandraMash approved these changes

2020-08-27 13:12 UTC, SavikPavel approved these changes

2020-08-27 13:13 UTC, merged