Rework TaskExceptionsTests
Softeq/XToolkit.WhiteLabel pull request #472
Opened 2022-02-01 17:43 UTC by wcoder

### Description

Rework `TaskExtensionsTests` to avoid using:
- `Task.Delay`
- `Skip` tests

### API Changes

 Removed:
 - `Task<T> WithTimeout<T>(this Task<T> task, TimeSpan timeout)`
 
### Platforms Affected

- Core (all platforms)

### Behavioral/Visual Changes

None

### Before/After Screenshots

Not applicable

### PR Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/Softeq/XToolkit.WhiteLabel/blob/master/.github/CONTRIBUTING.md) document
- [x] My code follows the [code styles](https://github.com/Softeq/dotnet-guidelines)
- [x] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2022-02-03 11:01 UTC, TimofeyBurak requested changes

2022-02-03 17:41 UTC, wcoder commented on Softeq.XToolkit.Common.Tests/Extensions/TaskExtensionsTests/TaskExtensionsTestsWithLoggingErrors.cs
> +        public void WithLoggingErrors_WhenLoggerIsNull_ThrowsArgumentNullException(bool generic)
I absolutely agree with you in common cases, but in this case (only result type different of calls that not used), I propose to keep with tests with flags.
The idea was: copypasting these tests for better readability is more complex to support in the future.

2022-02-03 17:42 UTC, wcoder commented
@TimofeyBurak thanks for the very helpful review. Could you please check the changes?

2022-02-17 15:12 UTC, wcoder commented on Softeq.XToolkit.Common.Tests/Extensions/TaskExtensionsTests/TaskExtensionsTestsWithTimeoutAsync.cs
> +            Assert.True(_taskStub.IsFaulted);
Good point about redundant checks, fixed!

2022-02-17 15:31 UTC, TimofeyBurak approved these changes

2022-02-17 15:32 UTC, merged